[[main]]
  name = "Home"
  weight = 10
  identifier = "home"
  pageRef = "/"


[[main]]
  name = "Docs"
  weight = 12
  identifier = "docs"
  pageRef = "/categories/docs/"
  pre = "bars"

[[main]]
  name = "Posts"
  weight = 30
  identifier = "archives"
  pageRef = "/post/"
  pre = "list"

[[main]]
  name = "연도별"
  weight = 31
  identifier = "yearly"
  parent = "archives"
  pageRef = "/years/"

[[main]]
  name = "카테고리"
  weight = 32
  identifier = "categories"
  parent = "archives"
  pageRef = "/categories/"

[[main]]
  name = "태그"
  weight = 33
  identifier = "tags"
  parent = "archives"
  pageRef = "/tags/"

[[main]]
  name = "시리즈"
  weight = 34
  identifier = "series"
  parent = "archives"
  pageRef = "/series/"

[[main]]
  name = "About"
  weight = 35
  identifier = "About"

[[main]]
  name = ""
  weight = 40
  identifier = "linkedin"
  pre = "linkedin"
  url = "https://www.linkedin.com/in/hyungyu-ethan-kim/"

[[main]]
  name = ""
  weight = 50
  identifier = "github"
  pre = "github"
  url = "https://github.com/babyworm"

