# This is a simple configuration.
# If you want to see the full configuration, please check `full-config.toml` .
# And see https://gohugo.io/getting-started/configuration/ .
baseURL = 'https://babyworm.github.io/'
title = 'Babyworm Hugo Site'
enableRobotsTXT = true
enableEmoji = true
theme = 'jane'
#languageCode = 'en-us'
#theme = 'hugo-theme-relearn'
#theme = 'zzo'

#defaultContentLanguage = "en" # Default language to use (if you setup multilingual)
#defaultContentLanguageInSubdir = true # baseURL/en/, baseURL/kr/ ...
hasCJKLanguage = true # Set `true` for Chinese/Japanese/Korean languages.

#paginate = 10  # Number of articles displayed on the homepage
summaryLength = 150 # The length of a post description on a list page.
#buildFuture = true # if true, we can use future date for talks pag
rssLimit = 20
enableGitInfo = true # When true, the modified date will appear on a summary and single page. Since GitHub info needs to be fetched, this feature will slow down to build depending on a page number you have
googleAnalytics = "G-5K5SXHWR3B"        # UA-XXXXXX-X
copyright = "© Babyworm, All Rights Reserved." # copyright symbol: $copy; current year: {year}
# timeout = 10000


[pagination]
  pagerSize = 10

[minify]
  minifyOutput = true

[services]
  [services.disqus]
    shortname = "babyworm-github-io"

defaultContentLanguage = "en"           # Default language to use
[languages.en]
  languageCode = "en"

[sitemap]                 # essential
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]             # config your menu              # 配置目录
  name = "Home"
  weight = 10
  identifier = "home"
  pageref = "/"
[[menu.main]]
  name = "Docs"
  weight = 12
  identifier = "docs"
  pageref = "/categories/docs/"
[[menu.main]]
  name = "Archives"
  weight = 20
  identifier = "archives"
  pageref = "/post/"
[[menu.main]]
  name = "Tags"
  weight = 130
  identifier = "tags"
  pageref = "/tags/"
[[menu.main]]
  name = "Categories"
  weight = 140
  identifier = "categories"
  pageref = "/categories/"


[mediaTypes]
  [mediaTypes."text/markdown"]
    suffixes = ["md", "mmark"]

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xHTML = true
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noHl = false
    style = 'friendly'
    tabWidth = 4

[outputs]
  home = ["HTML", "RSS"]
#   page = ['html', 'rss', 'print']
#   section = ['html', 'rss', 'print']

[outputFormats]
  [outputFormats.JSON]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true


[params]
  since = "2006"      # Site creation time
  homeFullContent = false   # if false, show post summaries on home page. Otherwise show full content.
  rssFullContent = true     # if false, Rss feed instead of the summary
  mainSections = ["post"]

  author.name = "babyworm"        # essential
  author.email = "babyworm@gmail.com" # optional, for RSS
  author.url = "/about"               # optional

  # Site Info
  logoTitle = "@babyworm"        # default: the title value
  keywords = ["Hugo", "theme","jane"]
  description = "Babyworm Tech. and Personal Blog."

  archive-paginate = 25

  # paginate style, default use numbered pagination links
  # if true, use original "Previous" and "Next" links.
  # paginateOriginalStyle = true

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  # show word count and read time ?                       # 是否显示字数统计与阅读时间
  moreMeta = true

  # show language chooser in menu
  showMenuLanguageChooser = true

  showAuthorInfo = true # show author info below the article

  editURL = 'https://github.com/babyworm/babyworm.github.io/edit/main/content'

  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc = true
  photoswipe = true  # see https://github.com/dimsemenov/PhotoSwipe
  mathjax = false           # see https://www.mathjax.org/                              # 是否使用mathjax（数学公式）
  katex = true             # see https://github.com/KaTeX/KaTeX
  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  #customCSS = ["css/search.css"]
  customCSS = []    # if ['custom.css'], load '/static/css/custom.css' file
  customJS = []     # if ['custom.js'], load '/static/js/custom.js' file


  showRelatedPosts = true
  showReadingTime = true
  showShareButtons = true

  [params.search.google]    # google custom search, see https://cse.google.com
    enable = true
    id = "c5a0e422652334df5"
    title = "Search"

  [params.disqus]
    autoLoad = false  # if true, load disqus when page loaded. Otherwise load disqus when user click the "Load Comments" button.

  [params.giscus]         # giscus is a comment system based on GitHub Discussions. see https://giscus.app
    enable = false
    repo = "babyworm/babyworm.github.io"
    repoId = "R_kgDOL3X7Wg"
    category = "Comments"
    categoryId = "DIC_kwDOL3X7Ws4CfduO"
    mapping = "pathname"  # comment value is the default value
    strict = 0
    reactionsEnabled = 1
    emitMetadata = 0
    inputPosition = "top"
    theme = "preferred_color_scheme"
    lang = "en"
    lazyLoading = false
    crossorigin = "anonymous"

  [params.social]
    a-email = "mailto:babyworm@gmail.com"
    b-linkedin = "https://www.linkedin.com/in/hyungyu-ethan-kim/"
    c-facebook = "https://www.facebook.com/ethan.hyungyu"
    d-stack-overflow = "https://stackoverflow.com/users/4914704/babyworm"
    f-github = "https://github.com/babyworm"



