[build]
  command = """
  curl -sSL https://github.com/sass/dart-sass-embedded/releases/download/1.93.2/sass_embedded-1.93.2-linux-x64.tar.gz \
    | tar -xz && \
  mv sass_embedded/dart-sass-embedded /opt/buildhome/bin/ && \
  npm ci && \
  PATH=/opt/buildhome/bin:$PATH hugo --gc --minify
  """
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.125.4"      # Netlify에서 설치할 Hugo 버전 (Extended 자동 사용)
  HUGO_ENABLEGITINFO = "true"
  GO_VERSION = "1.22.5"         # Hugo Modules 쓰거나 Go 기반 theme 빌드 시 필요
  TZ = "Asia/Seoul"             # 시간대 지정

[context.deploy-preview]
  command = "git submodule update --init --recursive --remote && npm ci && hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "git submodule update --init --recursive --remote && npm ci && hugo --gc --minify -b $DEPLOY_PRIME_URL"

