[build]
  command = "hugo --gc --minify --enableGitInfo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.151.0"      # Netlify에서 설치할 Hugo 버전 (Extended 자동 사용)
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  TZ = "Asia/Seoul"             # 시간대 지정

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"

# 프로덕션(main)
[context.production]
  command = "hugo --gc --minify --enableGitInfo"

[context.deploy-preview]
  command = "hugo --gc --minify --enableGitInfo -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify --enableGitInfo -b $DEPLOY_PRIME_URL"
