[build]
  command = "npm ci && PATH=\"$(pwd)/node_modules/.bin:$PATH\" HUGO_SASS_EXECUTABLE=dart-sass-embedded hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.151.0"      # Netlify에서 설치할 Hugo 버전 (Extended 자동 사용)
  HUGO_ENABLEGITINFO = "true"
  GO_VERSION = "1.22.5"         # Hugo Modules 쓰거나 Go 기반 theme 빌드 시 필요
  TZ = "Asia/Seoul"             # 시간대 지정

[context.deploy-preview]
  command = "npm ci && PATH=\"$(pwd)/node_modules/.bin:$PATH\" HUGO_SASS_EXECUTABLE=dart-sass-embedded hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "npm ci && PATH=\"$(pwd)/node_modules/.bin:$PATH\" HUGO_SASS_EXECUTABLE=dart-sass-embedded hugo --gc --minify -b $DEPLOY_PRIME_URL"
